// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: algorhitm.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RicartArgwalaService_RequestAccess_FullMethodName = "/grpc.RicartArgwalaService/RequestAccess"
	RicartArgwalaService_ReplyAccess_FullMethodName   = "/grpc.RicartArgwalaService/ReplyAccess"
)

// RicartArgwalaServiceClient is the client API for RicartArgwalaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RicartArgwalaServiceClient interface {
	// Called when a node wants to request access to the critical section.
	RequestAccess(ctx context.Context, in *RequestMessage, opts ...grpc.CallOption) (*Ack, error)
	// Called when a node replies to a request (grants permission).
	ReplyAccess(ctx context.Context, in *ReplyMessage, opts ...grpc.CallOption) (*Ack, error)
}

type ricartArgwalaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRicartArgwalaServiceClient(cc grpc.ClientConnInterface) RicartArgwalaServiceClient {
	return &ricartArgwalaServiceClient{cc}
}

func (c *ricartArgwalaServiceClient) RequestAccess(ctx context.Context, in *RequestMessage, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, RicartArgwalaService_RequestAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ricartArgwalaServiceClient) ReplyAccess(ctx context.Context, in *ReplyMessage, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, RicartArgwalaService_ReplyAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RicartArgwalaServiceServer is the server API for RicartArgwalaService service.
// All implementations must embed UnimplementedRicartArgwalaServiceServer
// for forward compatibility.
type RicartArgwalaServiceServer interface {
	// Called when a node wants to request access to the critical section.
	RequestAccess(context.Context, *RequestMessage) (*Ack, error)
	// Called when a node replies to a request (grants permission).
	ReplyAccess(context.Context, *ReplyMessage) (*Ack, error)
	mustEmbedUnimplementedRicartArgwalaServiceServer()
}

// UnimplementedRicartArgwalaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRicartArgwalaServiceServer struct{}

func (UnimplementedRicartArgwalaServiceServer) RequestAccess(context.Context, *RequestMessage) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestAccess not implemented")
}
func (UnimplementedRicartArgwalaServiceServer) ReplyAccess(context.Context, *ReplyMessage) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplyAccess not implemented")
}
func (UnimplementedRicartArgwalaServiceServer) mustEmbedUnimplementedRicartArgwalaServiceServer() {}
func (UnimplementedRicartArgwalaServiceServer) testEmbeddedByValue()                              {}

// UnsafeRicartArgwalaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RicartArgwalaServiceServer will
// result in compilation errors.
type UnsafeRicartArgwalaServiceServer interface {
	mustEmbedUnimplementedRicartArgwalaServiceServer()
}

func RegisterRicartArgwalaServiceServer(s grpc.ServiceRegistrar, srv RicartArgwalaServiceServer) {
	// If the following call pancis, it indicates UnimplementedRicartArgwalaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RicartArgwalaService_ServiceDesc, srv)
}

func _RicartArgwalaService_RequestAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RicartArgwalaServiceServer).RequestAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RicartArgwalaService_RequestAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RicartArgwalaServiceServer).RequestAccess(ctx, req.(*RequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _RicartArgwalaService_ReplyAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RicartArgwalaServiceServer).ReplyAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RicartArgwalaService_ReplyAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RicartArgwalaServiceServer).ReplyAccess(ctx, req.(*ReplyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// RicartArgwalaService_ServiceDesc is the grpc.ServiceDesc for RicartArgwalaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RicartArgwalaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.RicartArgwalaService",
	HandlerType: (*RicartArgwalaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestAccess",
			Handler:    _RicartArgwalaService_RequestAccess_Handler,
		},
		{
			MethodName: "ReplyAccess",
			Handler:    _RicartArgwalaService_ReplyAccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "algorhitm.proto",
}
