// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.20.3
// source: algorhitm.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NodeId           int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	LamportTimestamp int64                  `protobuf:"varint,2,opt,name=lamportTimestamp,proto3" json:"lamportTimestamp,omitempty"`
	FromAddr         string                 `protobuf:"bytes,3,opt,name=from_addr,json=fromAddr,proto3" json:"from_addr,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RequestMessage) Reset() {
	*x = RequestMessage{}
	mi := &file_algorhitm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMessage) ProtoMessage() {}

func (x *RequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_algorhitm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMessage.ProtoReflect.Descriptor instead.
func (*RequestMessage) Descriptor() ([]byte, []int) {
	return file_algorhitm_proto_rawDescGZIP(), []int{0}
}

func (x *RequestMessage) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *RequestMessage) GetLamportTimestamp() int64 {
	if x != nil {
		return x.LamportTimestamp
	}
	return 0
}

func (x *RequestMessage) GetFromAddr() string {
	if x != nil {
		return x.FromAddr
	}
	return ""
}

type ReplyMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NodeId           int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	LamportTimestamp int64                  `protobuf:"varint,2,opt,name=lamportTimestamp,proto3" json:"lamportTimestamp,omitempty"`
	FromAddr         string                 `protobuf:"bytes,3,opt,name=from_addr,json=fromAddr,proto3" json:"from_addr,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReplyMessage) Reset() {
	*x = ReplyMessage{}
	mi := &file_algorhitm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyMessage) ProtoMessage() {}

func (x *ReplyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_algorhitm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyMessage.ProtoReflect.Descriptor instead.
func (*ReplyMessage) Descriptor() ([]byte, []int) {
	return file_algorhitm_proto_rawDescGZIP(), []int{1}
}

func (x *ReplyMessage) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *ReplyMessage) GetLamportTimestamp() int64 {
	if x != nil {
		return x.LamportTimestamp
	}
	return 0
}

func (x *ReplyMessage) GetFromAddr() string {
	if x != nil {
		return x.FromAddr
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_algorhitm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_algorhitm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_algorhitm_proto_rawDescGZIP(), []int{2}
}

func (x *Ack) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_algorhitm_proto protoreflect.FileDescriptor

const file_algorhitm_proto_rawDesc = "" +
	"\n" +
	"\x0falgorhitm.proto\x12\x04grpc\"r\n" +
	"\x0eRequestMessage\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\x12*\n" +
	"\x10lamportTimestamp\x18\x02 \x01(\x03R\x10lamportTimestamp\x12\x1b\n" +
	"\tfrom_addr\x18\x03 \x01(\tR\bfromAddr\"p\n" +
	"\fReplyMessage\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\x12*\n" +
	"\x10lamportTimestamp\x18\x02 \x01(\x03R\x10lamportTimestamp\x12\x1b\n" +
	"\tfrom_addr\x18\x03 \x01(\tR\bfromAddr\"\x1f\n" +
	"\x03Ack\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2z\n" +
	"\x14RicartArgwalaService\x122\n" +
	"\rRequestAccess\x12\x14.grpc.RequestMessage\x1a\t.grpc.Ack\"\x00\x12.\n" +
	"\vReplyAccess\x12\x12.grpc.ReplyMessage\x1a\t.grpc.Ack\"\x00B\x17Z\x15example.com/grpc;grpcb\x06proto3"

var (
	file_algorhitm_proto_rawDescOnce sync.Once
	file_algorhitm_proto_rawDescData []byte
)

func file_algorhitm_proto_rawDescGZIP() []byte {
	file_algorhitm_proto_rawDescOnce.Do(func() {
		file_algorhitm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_algorhitm_proto_rawDesc), len(file_algorhitm_proto_rawDesc)))
	})
	return file_algorhitm_proto_rawDescData
}

var file_algorhitm_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_algorhitm_proto_goTypes = []any{
	(*RequestMessage)(nil), // 0: grpc.RequestMessage
	(*ReplyMessage)(nil),   // 1: grpc.ReplyMessage
	(*Ack)(nil),            // 2: grpc.Ack
}
var file_algorhitm_proto_depIdxs = []int32{
	0, // 0: grpc.RicartArgwalaService.RequestAccess:input_type -> grpc.RequestMessage
	1, // 1: grpc.RicartArgwalaService.ReplyAccess:input_type -> grpc.ReplyMessage
	2, // 2: grpc.RicartArgwalaService.RequestAccess:output_type -> grpc.Ack
	2, // 3: grpc.RicartArgwalaService.ReplyAccess:output_type -> grpc.Ack
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_algorhitm_proto_init() }
func file_algorhitm_proto_init() {
	if File_algorhitm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_algorhitm_proto_rawDesc), len(file_algorhitm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_algorhitm_proto_goTypes,
		DependencyIndexes: file_algorhitm_proto_depIdxs,
		MessageInfos:      file_algorhitm_proto_msgTypes,
	}.Build()
	File_algorhitm_proto = out.File
	file_algorhitm_proto_goTypes = nil
	file_algorhitm_proto_depIdxs = nil
}
